version: 0.2
phases:
  install:
     commands:
         - aws cloudformation package --region eu-west-2 --template-file samTemplate.yml  --s3-bucket pdpmalaths-lambda-pipeline  --output-template-file packaged-template.yml --stack-name mylambdastack
artifacts:
   type: zip
   files:
     - packaged-template.yml
