version: 0.2
phases:
  install:
     commands:
         - aws cloudformation package --template-file samTemplate.yml  --s3-bucket pdpmalaths-lambda-pipeline  --output-template-file packaged-template.yml
artifacts:
   type: zip
   files:
     - packaged-template.yml
